### ISSUE TITLE
[Bug] Entangled ME Controller

### ISSUE THREAD

**Issue by Lousheng** [SuperMartijn642/Entangled1.12#27]
**Version Info**
- Minecraft, 1.16.5
- Entangled, 1.3.6

**Description of the Bug**
Fluix cables don't connect to an entangled block linked to an me controller.

**Steps to Reproduce**
Bind entangle block to me controller.
Try to attach an me cable.

**Screenshots**
![image](https://user-images.githubusercontent.com/47648914/135760386-89e540f9-9f48-44eb-9047-df74de10e298.png)

**Comment by jpeaglesandkatz** [comment]
Yeh.. running into the same thing... Can't entangle controller, can't entangle p2p tunnels, cabels... Or you can but it doesn't do anything.. Latest AE2 on 1.19.2 (ATM8)

Not sure if anyone actually reads these issue logs as this one seemed to have been from 2021 already.

**Comment by SuperMartijn642** [comment]
I do read all these issues. I just have a lot of mods to maintain and update, and not a lot of time. This issue is relatively minor, so I prefer to work on higher priority stuff in the time I have.

In regards to the actual issue, the entangled blocks are not intended allow connecting Applied Energistics (AE2) networks through them. It is simply incompatible with AE2's network discovery.
The cable connected to the entangled block will tell the bound block 'hey I've been placed here on your west side, let's connect our networks'. Then when the bound block later tries to check for a block on it's west side, it won't find the cable or it might even find a different cable. This inherently leads to issues.

**Comment by SuperMartijn642** [comment]
I have now added a blacklist feature for target blocks. By default, all Applied Energistics blocks are now blacklisted to indicate you can't connect networks through the entangled block.
This is available in Entangled version 1.3.17.
Thank you for reporting the issue!

**Comment by ShadowFox88** [comment]
This would result in the ME Interface being blacklisted as well, so if possible could you whitelist just that block?

**Comment by HeatherComputer** [comment]
I really don't see this as deserving a blacklist.

Entangled forwards capabilities, no? It makes sense for RS, AE2 etc to be unable to form networks through entangled blocks. That's fine, they have their own wireless solutions.

But what they *don't* have solutions for is wireless moving of items, fluids etc. 
If a pattern provider were to push into an entangled machine, that'd work fine. But then if that machine wanted to eject...

The natural solution to that is to entangle the pattern provider, but that's not doable with the blacklist.
