### ISSUE TITLE
[Feature] Accessing connected blocks inventory/GUI through the Entangled Block

### ISSUE THREAD

**Issue by LocoCubano** [SuperMartijn642/Entangled1.12#32]
**Is your feature request related to a problem? Please describe.**
Sometimes the reason you use this lovely Entangled Block is because directly accessing the machine it is tied to normally is difficult or not desired due to having to break blocks you'd rather not. It would be great to be able to access the blocks interface.

**Describe the solution you'd like**
Add the ability to click on the Entangled Block to access the connected blocks GUI, could be done with empty hand or with a Entangled Binder or a new tool to allow this function.

Assuming this is even possible, I have no idea. 😅

**Comment by SuperMartijn642** [comment]
Thank you for the suggestion!

The suggestion is part of the suggestion in #28. These are the main problems I had with the idea:
> I originally [allowed interacting with the bound block], but there are some problems with it mostly related to guis:
> 1. All the vanilla inventory screens and most modded ones close when the player is more than 64 blocks away. This means that if the entangled block is far away, the inventory opens for a split second and then immediately closes.
> 2. I would have to prevent the chunks from being unloaded while an inventory from an entangled block is open. Otherwise the chunk would unload while the player has it open and changes to the inventory won't get saved, leading to duplication or loss of items.
> 3. Blocks expect an interacting player to be in the same dimension. This can have a lot of unintended effects like placing stuff at the player's coordinates in the wrong dimension.
I might be able to solve number 2 by temporarily keeping the chunk loaded, however 1 and 3 very much depend on the underlying mods' implementation, so I can't solve those. With the guis opening and closing instantly, it very much feels like a bug in the mod.

To conclude, I likely won't be adding the suggestion due to the mentioned issues, but I'll have to properly look into it at a later date.
I will close this issue in favor of #28.
