### ISSUE TITLE
[Bug] Unable to Unbind Entangled Block

### ISSUE THREAD

**Issue by LilMxPlagueRat** [SuperMartijn642/Entangled1.12#52]
**Version Info**
- Minecraft, 1.18.2
- Entangled, 1.3.11 (through the FTB Stoneblock 3 Modpack)

**Description of the Bug**
When Sneak + Right-clicking on an Entangled Block with an empty hand the Entangled Block is not becoming Unbound

**Steps to Reproduce**
1. Bind Entangled Block to any other block
2. Select an empty hand
3. Hold Sneak Key and Right click
4. Entangled Block is still bound

**Screenshots**
I'm not sure how to show this in screenshots

**Comment by SuperMartijn642** [comment]
This appears to be working fine with just Entangled 1.3.11 (and 1.3.12) and my core and config libraries.
Could you check if the issue persists with just Entangled and if not, narrow down the mods needed to reproduce it?

**Comment by LilMxPlagueRat** [comment]
> and

I'm not actually sure how to do that, as I've never modded without using a mod pack and I'm not sure what mods rely of what in the pack

**Comment by SuperMartijn642** [comment]
In that case it's probably best to report the issue to Stoneblock 3. You can find the repository for FTB packs here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues

**Comment by Lordmau5** [comment]
So I've just encountered this as well and noticed it threw some errors in the server console.
I've also opened an issue on the FTB repo you linked here: https://github.com/FTBTeam/FTB-Modpack-Issues/issues/2859

The error mentions something in the `canBindTo` method about not being able to invoke a Vector method because the variable is null.
https://pste.ch/takutogiva.pl

Upon checking, it seems like the code is only checking if **both** `pos` and `dimension` are null, not individually.
https://github.com/SuperMartijn642/Entangled/blob/1.18/src/main/java/com/supermartijn642/entangled/EntangledBlockEntity.java#L148

I'm not sure which mod changes the BlockPos to null there through some mixin, but at least that's where it seems to happen...
