### ISSUE TITLE
Entangled block crashes client when paired with Modern Industrialization energy source

### ISSUE THREAD

**Issue by Shoki17** [SuperMartijn642/Entangled1.12#61]
**Version Info** Fabric 0.76.0
- Minecraft, ...1.19.2
- Entangled, ...

**Steps to Reproduce**
...Place entangled block next to Modern Industrialization machine (single block) and link a turbine or storage unit to the entangled block. Wait at least 5 minutes (maybe less) and the client will crash. When trying to login again, the client will continue to crash until the entangled block is removed from the world. 
[crash-2023-06-11_17.42.43-client.txt](https://github.com/SuperMartijn642/Entangled/files/11716092/crash-2023-06-11_17.42.43-client.txt)

**Crash report (~/logs/latest.log)**
...

**Comment by SuperMartijn642** [comment]
Seems to be caused by Modern Industrialization. I have submitted an issue for it and a pull request to fix it https://github.com/AztechMC/Modern-Industrialization/issues/512

Most likely it is caused by entangling a pipe from Modern Industrialization, so you should avoid that until an updated version of Modern Industrialization is released.
