### ISSUE TITLE
[Crash] Crash when entangling an Industrial Foregoing machine

### ISSUE THREAD

**Issue by TheL0ki** [SuperMartijn642/Entangled1.12#8]
**Version Info**
- Minecraft: 1.16.4
- Entangled, 1.2.7

**Steps to Reproduce**
Entangle a Industrial Foregoing machine.
I was testing this mod in the modpack "All the mods 6". When I entangled an machine from Industrial Foregoing (A new one, can't remember the name sorry) the server crashed when I tried to right click the Entangler block and I can't get it to start since. I've attached the latest crashlog. As this was my very first try I can't say for sure if this happens with other blocks too.

**Crash report (~/logs/latest.log)**
[latest.log](https://github.com/SuperMartijn642/Entangled1.12/files/5588526/latest.log)

**Comment by TheL0ki** [comment]
I did some further testing. After removing the mod both client and server side, I could start up again. I've added it in again afterwards and the entanglement with the machine was gone. (Dissolution Chamber btw)

I then tried to entangle a vanilla furnace but as soon as I entangled it with the binder the server crashed again. (latest log provided)
[latest.log](https://github.com/SuperMartijn642/Entangled1.12/files/5589053/latest.log)

**Comment by SuperMartijn642** [comment]
Turns out I mapped one of the functions incorrectly when porting to 1.16.4. Because of that the dimension was saved incorrectly and the world crashes when it tries to load an entangled block.
I fixed it in version 1.2.8, sadly all entangled blocks previously saved in 1.16.4 will have to be relinked.

Thank you for reporting the issue!
