### ISSUE TITLE
[Bug] On the server side, The One Probe aligned with the bound entangled block will display a string of garbled code.

### ISSUE THREAD

**Issue by xiaojing911** [SuperMartijn642/Entangled1.12#84]
**Version Info**
- Minecraft, 1.12.2
- Entangled, 1.3.18a

**Description of the Bug**
On the server side, The One Probe aligned with the bound entangled block will display a string of garbled code.

**Steps to Reproduce**
1. Log in to the server.
2. Place the entangled block.
3. Bind the entangled block.

**Screenshots**
![image](https://github.com/SuperMartijn642/Entangled/assets/166046962/a46129b3-e6db-4ace-b750-1d467d61a503)

**Comment by SuperMartijn642** [comment]
This is a limitation of The One Probe. The One Probe determines its component's contents server-side and then sends it to the client. As The One Probe only allows for literal text and not translation components, there is no way to resolve the translation keys on the client. Hence, you are just seeing the translation key.

I have made it so the The One Probe integration will just send the English version when on a dedicated server. This is sadly the best I can do. I would suggest using [Hwyla](https://www.curseforge.com/minecraft/mc-mods/hwyla) instead of The One Probe.
Anyways, thank you for reporting the issue!
