### ISSUE TITLE
[Crash] Entangling a chest in the overworld to the nether and hoppers

### ISSUE THREAD

**Issue by Gaz492** [SuperMartijn642/Entangled1.12#95]
**Version Info**
- Minecraft, 1.21.1
- Entangled, 1.3.19

**Steps to Reproduce**
1. Place chest in overworld
2. Shift right click the chest with the entangle binder
3. Go to the nether
4. Place entangle block down
5. Right click the entangled block
6. Attach hopper to the block
7. Place an item in the hopper
8. Crash

**Crash report (~/logs/latest.log)**
https://pste.me/@4dsfMu_VmTE

**Comment by SuperMartijn642** [comment]
It seems I accidentally queried capabilities for the bound block from the dimension the entangled block is located in rather than the one the bound block is actually in. Likely just an oversight from whenever I made a NeoForge version of Entangled, whoops.
Should be fixed now in version 1.3.19a of Entangled for NeoForge 1.20.4 - 1.21.1.
Thank you for reporting the issue!
